- name: Deploy web app to EC2
  hosts: web
  become: yes
  tasks:
    - name: Update apt cache (for Debian)
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Install libcrypt1 for Docker Compose (Debian)
      apt:
        name: libcrypt1
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker (Debian)
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker (Amazon Linux)
      shell: |
        if ! command -v docker; then
          if command -v amazon-linux-extras; then
            sudo amazon-linux-extras install docker -y
          else
            sudo dnf install docker -y
          fi
        fi
      when: ansible_os_family == "RedHat"

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose (universal)
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Symlink docker-compose to /usr/bin
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link
        force: yes

    - name: Ensure /home/ec2-user directory exists
      file:
        path: /home/ec2-user
        state: directory
        owner: ec2-user
        group: ec2-user

    - name: Copy application files
      copy:
        src: "../roles/web/files/{{ item }}"
        dest: "/home/ec2-user/{{ item }}"
        owner: ec2-user
        group: ec2-user
        mode: '0644'
      loop:
        - app.py
        - requirements.txt
        - Dockerfile
        - docker-compose.yml

    - name: Run Docker Compose
      shell: |
        cd /home/ec2-user && docker-compose down || true
        cd /home/ec2-user && docker-compose up -d
      args:
        executable: /bin/bash